use joins;
SELECT*FROM STUDENT INNER JOIN COURSE ON STUDENT.ID = COURSE.STUDENT_ID;

SELECT*FROM STUDENT S INNER JOIN COURSE C ON S.ID=C.STUDENT_ID;

SELECT*FROM STUDENT AS S INNER JOIN COURSE AS C ON S.ID=C.STUDENT_ID;

SELECT*FROM STUDENT AS S LEFT JOIN COURSE AS C ON S.ID=C.STUDENT_ID;

SELECT*FROM STUDENT AS S RIGHT JOIN COURSE AS C ON S.ID=C.STUDENT_ID;

SELECT*FROM STUDENT AS S LEFT JOIN COURSE AS C ON S.ID=C.STUDENT_ID UNION SELECT*FROM STUDENT AS S RIGHT JOIN COURSE AS C ON S.ID=C.STUDENT_ID;

SELECT*FROM STUDENT AS S LEFT JOIN COURSE AS C ON S.ID=C.STUDENT_ID UNION ALL SELECT*FROM STUDENT AS S RIGHT JOIN COURSE AS C ON S.ID=C.STUDENT_ID;

SELECT NAME ,COURSE FROM STUDENT INNER JOIN COURSE ON STUDENT.ID=COURSE.STUDENT_ID; 

SELECT ID FROM STUDENT EXCEPT SELECT STUDENT_ID FROM COURSE;

SELECT ID FROM STUDENT S LEFT JOIN COURSE C ON S.ID=C.STUDENT_ID WHERE C.STUDENT_ID IS NULL;

